browserType=chrome
testUrl_saf=https://my.safmarine.com
testUrl_CT=https://www.cleartrip.com
testUrl_sauce=https://www.saucedemo.com
testDataExcel=src/main/resources/TestData/TestData.xlsx
extent-xmlConfigPath=extent_Config.xml
extentReportLocation=testResults/Extent_Report.html
